name: dmarc-analyzer
region: nyc
services:
  - name: frontend
    source_dir: /frontend
    github:
      repo: YOUR_GITHUB_USERNAME/dmarc-analyzer
      branch: main
      deploy_on_push: true
    build_command: npm ci && npm run build
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb
    http_port: 3000
    routes:
      - path: /
    envs:
      - key: NEXT_PUBLIC_SUPABASE_URL
        value: https://kvbqrdcehjrkoffzjfmh.supabase.co
        scope: RUN_TIME
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2YnFyZGNlaGpya29mZnpqZm1oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5OTg2NjgsImV4cCI6MjA2NDU3NDY2OH0.DEor3A0HjrDA2d-JnxQJphDf3pzJCQ0ofShShEjraLg
        scope: RUN_TIME
  - name: backend
    source_dir: /backend
    github:
      repo: YOUR_GITHUB_USERNAME/dmarc-analyzer
      branch: main
      deploy_on_push: true
    build_command: pip install -r requirements.txt
    run_command: uvicorn main:app --host 0.0.0.0 --port 8000
    environment_slug: python
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb
    http_port: 8000
    routes:
      - path: /api
    envs:
      - key: SUPABASE_URL
        value: https://kvbqrdcehjrkoffzjfmh.supabase.co
        scope: RUN_TIME
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: YOUR_SUPABASE_SERVICE_ROLE_KEY
        scope: RUN_TIME
        type: SECRET
workers:
  - name: dmarc-scheduler
    source_dir: /backend
    github:
      repo: YOUR_GITHUB_USERNAME/dmarc-analyzer
      branch: main
      deploy_on_push: true
    build_command: pip install -r requirements.txt
    run_command: python scheduler.py
    environment_slug: python
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    envs:
      - key: SUPABASE_URL
        value: https://kvbqrdcehjrkoffzjfmh.supabase.co
        scope: RUN_TIME
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: YOUR_SUPABASE_SERVICE_ROLE_KEY
        scope: RUN_TIME
        type: SECRET 