name: Deploy to DigitalOcean Droplet

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to DigitalOcean Droplet
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DROPLET_HOST }}
        username: ${{ secrets.DROPLET_USER }}
        key: ${{ secrets.DROPLET_SSH_KEY }}
        script: |
          # Navigate to app directory
          cd /opt/dmarc-analyzer || (sudo mkdir -p /opt/dmarc-analyzer && cd /opt/dmarc-analyzer && sudo chown $USER:$USER /opt/dmarc-analyzer)
          
          # Clone or update repository
          if [ -d ".git" ]; then
            echo "Updating existing repository..."
            git pull origin main
          else
            echo "Cloning repository..."
            git clone https://github.com/${{ github.repository }}.git .
          fi
          
          # Create environment file
          cat > .env << 'EOF'
          SUPABASE_URL=${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          NEXT_PUBLIC_API_URL=https://dmarc.sharanprakash.me
          EOF
          
          # Make deploy script executable
          chmod +x deploy.sh
          
          # Perform zero-downtime deployment
          echo "Starting zero-downtime deployment..."
          ./deploy.sh deploy
          
          # Show final status
          echo "Deployment complete!"
          ./deploy.sh status 